kind: Deployment
apiVersion: apps/v1
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: "openzipkin/zipkin:latest"
          ports:
            - containerPort: 9411
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
  selector:
    app: zipkin
