kind: ConfigMap
apiVersion: v1
metadata:
  name: filebeat-config
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      paths: ["/usr/app/logs/*.log"]
    output.logstash:
      hosts: ["logstash.elastic-stack.svc.cluster.local:5044"]
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccount: filebeat
      containers:
        - image: docker.elastic.co/beats/filebeat:7.12.1
          args:
            - "-c"
            - /etc/filebeat.yml
            - "-e"
          securityContext:
            privileged: true
          name: filebeat
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
            - name: app-logs
              mountPath: /usr/app/logs
        - name: generate-log
          image: busybox
          command: ["sh", "-c", "while true; do date >> /workdir/date.log; sleep 2; done;"]
          volumeMounts:
            - mountPath: /workdir
              name: app-logs
      volumes:
        - name: config
          configMap:
            name: filebeat-config
            defaultMode: 420
        - name: app-logs
          emptyDir: {}
