kind: ConfigMap
apiVersion: v1
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /usr/app/logs/*.log
    filebeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    setup.template.settings:
      index.number_of_shards: 1
    fields:
      appname: ${POD_NAME}
    setup.kibana:
    output.logstash:
      hosts: ["logstash:5000"]
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: filebeat
    spec:
      containers:
        - resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          name: filebeat
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
            - name: app-logs
              mountPath: /usr/app/logs
          image: "docker.elastic.co/beats/filebeat:7.5.1"
          args:
            - "-c"
            - /etc/filebeat.yml
            - "-e"
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/nginx
      serviceAccount: filebeat
      volumes:
        - name: config
          configMap:
            name: filebeat-config
            defaultMode: 420
        - name: app-logs
          emptyDir: {}
