apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: >-
            docker.elastic.co/kibana/kibana:7.12.1
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch-0.es.default.svc.cluster.local:9200
            - name: ELASTICSEARCH_HOSTS
              value: '["http://elasticsearch-0.es.default.svc.cluster.local:9200","http://elasticsearch-1.es.default.svc.cluster.local:9200","http://elasticsearch-2.es.default.svc.cluster.local:9200"]'
---
kind: Service
apiVersion: v1
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  selector:
    app: kibana
