apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: >-
            docker.elastic.co/logstash/logstash:7.12.1
          ports:
            - containerPort: 5044
            - containerPort: 5000
            - containerPort: 9600
          env:
            - name: ELASTICSEARCH_URL
              value: http://es:9200
          volumeMounts:
            - name: logstash-config
              readOnly: true
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: logstash-pipline-config
              readOnly: true
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: logstash-config
          configMap:
            name: logstash.yml
            defaultMode: 420
        - name: logstash-pipline-config
          configMap:
            name: logstash.conf
            defaultMode: 420
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  selector:
    app: logstash
