apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
  namespace: xcxu
spec:
  selector:
    matchLabels:
      app: es
  replicas: 1
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: >-
            docker.elastic.co/elasticsearch/elasticsearch:7.12.1
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
---
kind: Service
apiVersion: v1
metadata:
  name: es
  namespace: xcxu
  labels:
    app: es
spec:
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    app: es
