http.host: "0.0.0.0"
# xpack.monitoring.enabled: true
# xpack.monitoring.elasticsearch.username: elastic
# xpack.monitoring.elasticsearch.password: xxxxx
# xpack.monitoring.elasticsearch.hosts: ["http://es01:9200","http://es02:9200","http://es03:9200"]
